languageCode = "en-us"
title = "My New Hugo Site"
baseURL = "http://example.org/"
theme = "daniel_cv"
enableRobotsTXT = true
DisableRSS = true
DisableSitemap = true
googleAnalytics = "UA-96539286-1"

[params.profile]
    first_name = "Daniel"
    last_name = "Peppicelli"
    tagline = "Full Stack Engineer"
    summary = """I'm a **full stack engineer** with 8 years of experience and I just completed a one year travel break around the world. Highly passionated by software and computer in general, you will find me hacking around with a soldering iron and a Raspberry PI when I'm not reading the latest items on [Hacker News](https://news.ycombinator.com/news).

Now that I'm back in Switzerland, I'm looking for any opportunities with **good software challenges** and a **solid team spirit**"""
    phone = "+41788281082"
    email = "daniel.peppicelli@gmail.com"
    picture = "profile.jpg"
    birthday = "30.01.1983"
    nationality = "Swiss"
    address = "Samson Reymondin 28, Pully"
[blackfriday]
  hrefTargetBlank = true
