languageCode = "en-us"
title = "My New Hugo Site"
baseURL = "https://peppicelli.github.io/"
theme = "hugo-resume"
enableRobotsTXT = true
DisableRSS = true
DisableSitemap = true
googleAnalytics = "UA-96539286-1"
defaultContentLanguage = "en"
relativeURLs = true
EnableMissingTranslationPlaceholders = true
defaultContentLanguageInSubdir = true

[params.profile]
first_name = "Daniel"
last_name = "Peppicelli"
phone = "+41788281082"
email = "daniel.peppicelli@gmail.com"
picture = "profile.jpg"
birthday = "30.01.1983"
tagline = "C++, embedded & Web Engineer"
address = "Samson Reymondin 28, Pully"
availability = "Available for small missions and consultancy (2019)."
github = "https://github.com/peppicelli"
summary = """I'm a **C++, embedded & Web engineer** with 10 years of experience. Highly passionated by software and computer in general, you will find me hacking around with a soldering iron and a Raspberry PI when I'm not reading the latest items on [Hacker News](https://news.ycombinator.com/news)."""
nationality = "Swiss"

[Languages]
[Languages.en]
weight = 20


[Languages.fr]
weight = 20
[Languages.fr.profile]
first_name = "Daniel"
last_name = "Peppicelli"
phone = "+41788281082"
email = "daniel.peppicelli@gmail.com"
picture = "profile.jpg"
birthday = "30.01.1983"
tagline = "Ingénieur C++, embarqué et Web"
address = "Samson Reymondin 28, Pully"
availability = "Disponible pour de petites missions et du consulting (2019)."
github = "https://github.com/peppicelli"
summary = """**Ingénieur C++, embarqué et Web** avec 10 ans d'expériences professionnelles. Passionné par le développement logiciel et par l'informatique en général, vous me trouverez fréquemment avec un fer à souder dans la main, en train de programmer sur un Raspberry PI ou à lire les derniers articles sur [Hacker News](https://news.ycombinator.com/news)."""
nationality = "Suisse"

[blackfriday]
  hrefTargetBlank = true
